CXX = g++
CXXFLAGS = -std=c++17 -Wall
TARGET = ejecutable.out
SOURCE = alfabeto.cc cadena.cc lenguaje.cc funciones.cc main.cc

$(TARGET): $(SOURCE)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCE)

clean:
	rm -f $(TARGET)